# SuperAdmins - full access to all accounts
SuperAdmins:
  principal: SuperAdmins
  principal_type: GROUP
  permission_sets:
    - AdministratorAccess
  account_list:
    - sandbox_dev
    - prod
    - audit

# PlatformAdmins - full access everywhere
PlatformAdmins:
  principal: PlatformAdmins
  principal_type: GROUP
  permission_sets:
    - AdministratorAccess
  account_list:
    - sandbox_dev
    - prod
    - audit

# Developers - dev access
DevelopersSandbox:
  principal: Developers
  principal_type: GROUP
  permission_sets:
    - DeveloperAccess
  account_list:
    - sandbox_dev

# Developers - prod read-only
DevelopersProd:
  principal: Developers
  principal_type: GROUP
  permission_sets:
    - SecurityAuditorFull
  account_list:
    - prod

# DevOps - infrastructure management
DevOpsEngineers:
  principal: DevOpsEngineers
  principal_type: GROUP
  permission_sets:
    - InfrastructureAdmin
  account_list:
    - sandbox_dev
    - prod

# Security Auditors - read-only everywhere
SecurityAuditors:
  principal: SecurityAuditors
  principal_type: GROUP
  permission_sets:
    - SecurityAuditorFull
  account_list:
    - sandbox_dev
    - prod
    - audit
