AdministratorAccess:
  description: Full administrative access
  session_duration: PT8H
  managed_policy_arns:
    - arn:aws:iam::aws:policy/AdministratorAccess

DeveloperAccess:
  description: Application development access
  session_duration: PT4H
  inline_policy_file: policies/permission_sets/developer_access.json

InfrastructureAdmin:
  description: Infrastructure management access
  session_duration: PT4H
  inline_policy_file: policies/permission_sets/infrastructure_admin.json

SecurityAuditor:
  description: Security audit and compliance access
  session_duration: PT4H
  managed_policy_arns:
    - arn:aws:iam::aws:policy/SecurityAudit

SecurityAuditorFull:
  description: Security audit with read-only access
  session_duration: PT4H
  managed_policy_arns:
    - arn:aws:iam::aws:policy/SecurityAudit
    - arn:aws:iam::aws:policy/ReadOnlyAccess

# Example: Using customer managed policies
# IMPORTANT: Customer managed policies must exist in target accounts BEFORE applying this configuration
#
# CustomDeveloperAccess:
#   description: Custom developer access with customer managed policies
#   session_duration: PT4H
#   managed_policy_arns:
#     - arn:aws:iam::aws:policy/ReadOnlyAccess
#   customer_managed_policy_references:
#     - name: CustomS3AccessPolicy      # Policy name in target accounts
#       path: /                          # Optional: IAM policy path (default: /)
#     - name: CustomLambdaAccessPolicy
#       path: /custom/policies/